/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.assignmentController;
import Controller.subjectController;
import Model.assignment;
import Model.subject;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashera
 */
public class add_assignments extends javax.swing.JFrame {
    /**
     * Creates new form add_assignment
     */
    public add_assignments() {
        initComponents();
        homeButton.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignmentHeader = new javax.swing.JPanel();
        assignmentHeader_Label = new javax.swing.JLabel();
        home_Label = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        paymentDetails = new javax.swing.JPanel();
        subjectCode_Label = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        subjectCode = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        weight_Label = new javax.swing.JLabel();
        assignmentWeight = new javax.swing.JTextField();
        assignmentType_Label = new javax.swing.JLabel();
        assignmentType = new javax.swing.JTextField();
        addAssignmentButton = new javax.swing.JButton();
        removeAssignmentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        assignmentsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        assignmentHeader.setBackground(new java.awt.Color(36, 47, 65));
        assignmentHeader.setLayout(null);

        assignmentHeader_Label.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        assignmentHeader_Label.setForeground(new java.awt.Color(255, 255, 255));
        assignmentHeader_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignmentHeader_Label.setText("ADD ASSIGNMENTS");
        assignmentHeader.add(assignmentHeader_Label);
        assignmentHeader_Label.setBounds(0, 13, 900, 64);

        home_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        assignmentHeader.add(home_Label);
        home_Label.setBounds(0, 0, 90, 90);

        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        assignmentHeader.add(homeButton);
        homeButton.setBounds(0, 0, 90, 90);

        getContentPane().add(assignmentHeader);
        assignmentHeader.setBounds(0, 0, 930, 90);

        paymentDetails.setBackground(new java.awt.Color(97, 212, 195));
        paymentDetails.setLayout(null);

        subjectCode_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        subjectCode_Label.setText("Subject Code");
        paymentDetails.add(subjectCode_Label);
        subjectCode_Label.setBounds(100, 110, 210, 30);

        doneButton.setBackground(new java.awt.Color(36, 47, 65));
        doneButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(doneButton);
        doneButton.setBounds(500, 430, 120, 50);

        subjectCode.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        subjectCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCodeActionPerformed(evt);
            }
        });
        paymentDetails.add(subjectCode);
        subjectCode.setBounds(310, 110, 230, 30);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(backButton);
        backButton.setBounds(330, 430, 120, 50);

        weight_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        weight_Label.setText("Weight");
        paymentDetails.add(weight_Label);
        weight_Label.setBounds(100, 190, 210, 30);

        assignmentWeight.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        assignmentWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentWeightActionPerformed(evt);
            }
        });
        paymentDetails.add(assignmentWeight);
        assignmentWeight.setBounds(310, 190, 230, 30);

        assignmentType_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        assignmentType_Label.setText("Assignment Type");
        paymentDetails.add(assignmentType_Label);
        assignmentType_Label.setBounds(100, 150, 210, 30);

        assignmentType.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        assignmentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentTypeActionPerformed(evt);
            }
        });
        paymentDetails.add(assignmentType);
        assignmentType.setBounds(310, 150, 230, 30);

        addAssignmentButton.setBackground(new java.awt.Color(36, 47, 65));
        addAssignmentButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        addAssignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        addAssignmentButton.setText("Add");
        addAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAssignmentButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(addAssignmentButton);
        addAssignmentButton.setBounds(650, 130, 80, 30);

        removeAssignmentButton.setBackground(new java.awt.Color(36, 47, 65));
        removeAssignmentButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        removeAssignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        removeAssignmentButton.setText("Remove");
        removeAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAssignmentButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(removeAssignmentButton);
        removeAssignmentButton.setBounds(650, 180, 80, 30);

        assignmentsTable.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        assignmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Assignment Type", "Weight(%)"
            }
        ));
        jScrollPane1.setViewportView(assignmentsTable);

        paymentDetails.add(jScrollPane1);
        jScrollPane1.setBounds(145, 250, 610, 150);

        getContentPane().add(paymentDetails);
        paymentDetails.setBounds(0, 0, 920, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) assignmentsTable.getModel();
        for (int i=0;i<assignmentsTable.getRowCount();i++){
            assignment Assignment = new assignment(model.getValueAt(i, 0).toString(),model.getValueAt(i, 1).toString(),model.getValueAt(i, 2).hashCode());
            try{
                int result = assignmentController.addAssignment(Assignment);
                if ( result<=0 )
                    JOptionPane.showMessageDialog(this,"Error");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
        model.setRowCount(0);
        JOptionPane.showMessageDialog(this, "Successfully Updated Assignments");
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void subjectCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodeActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new manage_results().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void assignmentWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentWeightActionPerformed

    private void assignmentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentTypeActionPerformed

    private void addAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAssignmentButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) assignmentsTable.getModel();
        String subject_code = subjectCode.getText();
        String assignment_type = assignmentType.getText();
        int weight = Integer.parseInt(assignmentWeight.getText());
        
        try{
            subject subjectCheck = subjectController.searchSubject(subject_code);
            if (subjectCheck!=null){
                model.addRow(new Object[]{subject_code,assignment_type,weight});
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid Subject Code");
                subjectCode.setText(null);
                assignmentType.setText(null);
                assignmentWeight.setText(null);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_addAssignmentButtonActionPerformed

    private void removeAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAssignmentButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) assignmentsTable.getModel();
        if(assignmentsTable.getSelectedRow()==-1){
            if(assignmentsTable.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Table is Empty");
            else
                JOptionPane.showMessageDialog(this, "Please Select a Row");
        }
        else{
            model.removeRow(assignmentsTable.getSelectedRow());
        }
    }//GEN-LAST:event_removeAssignmentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_assignments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAssignmentButton;
    private javax.swing.JPanel assignmentHeader;
    private javax.swing.JLabel assignmentHeader_Label;
    private javax.swing.JTextField assignmentType;
    private javax.swing.JLabel assignmentType_Label;
    private javax.swing.JTextField assignmentWeight;
    private javax.swing.JTable assignmentsTable;
    private javax.swing.JButton backButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel home_Label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paymentDetails;
    private javax.swing.JButton removeAssignmentButton;
    private javax.swing.JTextField subjectCode;
    private javax.swing.JLabel subjectCode_Label;
    private javax.swing.JLabel weight_Label;
    // End of variables declaration//GEN-END:variables
}
