/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.subjectController;
import Model.subject;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashera
 */
public class add_subject extends javax.swing.JFrame {

    /**
     * Creates new form add_subject
     */
    public add_subject() {
        initComponents();
        homeButton.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isCompulsory = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        signupHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home_Label = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        subjectCode_Label = new javax.swing.JLabel();
        name_Label = new javax.swing.JLabel();
        courseID_Label = new javax.swing.JLabel();
        semesterID_Label = new javax.swing.JLabel();
        lecturerID_Label = new javax.swing.JLabel();
        isCompulsory_label = new javax.swing.JLabel();
        subjectCode = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        semesterID = new javax.swing.JTextField();
        lecturerID = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        No = new javax.swing.JRadioButton();
        yes = new javax.swing.JRadioButton();
        courseID = new javax.swing.JTextField();
        credits = new javax.swing.JTextField();
        address_Label = new javax.swing.JLabel();
        fee_Label = new javax.swing.JLabel();
        fee = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        day_Label = new javax.swing.JLabel();
        timeSlot_Label = new javax.swing.JLabel();
        lectureHall_Label = new javax.swing.JLabel();
        timeSlot = new javax.swing.JTextField();
        lectureHall = new javax.swing.JTextField();
        dayCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.setLayout(null);

        signupHeader.setBackground(new java.awt.Color(36, 47, 65));
        signupHeader.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD SUBJECT");
        signupHeader.add(jLabel1);
        jLabel1.setBounds(0, 13, 900, 64);

        home_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        signupHeader.add(home_Label);
        home_Label.setBounds(0, 0, 90, 90);

        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        signupHeader.add(homeButton);
        homeButton.setBounds(0, 0, 90, 90);

        jPanel3.add(signupHeader);
        signupHeader.setBounds(0, 0, 930, 90);

        subjectCode_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        subjectCode_Label.setText("Subject Code");
        jPanel3.add(subjectCode_Label);
        subjectCode_Label.setBounds(30, 150, 160, 30);

        name_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        name_Label.setText("Name");
        jPanel3.add(name_Label);
        name_Label.setBounds(30, 190, 160, 30);

        courseID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        courseID_Label.setText("Course ID");
        jPanel3.add(courseID_Label);
        courseID_Label.setBounds(30, 310, 160, 30);

        semesterID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semesterID_Label.setText("Semester ID");
        jPanel3.add(semesterID_Label);
        semesterID_Label.setBounds(450, 150, 180, 30);

        lecturerID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lecturerID_Label.setText("Lecturer ID");
        jPanel3.add(lecturerID_Label);
        lecturerID_Label.setBounds(450, 190, 160, 30);

        isCompulsory_label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        isCompulsory_label.setText("Is Compulsory");
        jPanel3.add(isCompulsory_label);
        isCompulsory_label.setBounds(30, 390, 210, 30);

        subjectCode.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        subjectCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCodeActionPerformed(evt);
            }
        });
        jPanel3.add(subjectCode);
        subjectCode.setBounds(190, 152, 230, 30);

        name.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel3.add(name);
        name.setBounds(190, 191, 230, 30);

        semesterID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        semesterID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterIDActionPerformed(evt);
            }
        });
        jPanel3.add(semesterID);
        semesterID.setBounds(640, 150, 230, 30);

        lecturerID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lecturerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerIDActionPerformed(evt);
            }
        });
        jPanel3.add(lecturerID);
        lecturerID.setBounds(640, 190, 230, 30);

        addButton.setBackground(new java.awt.Color(36, 47, 65));
        addButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addButton);
        addButton.setBounds(750, 420, 120, 50);

        isCompulsory.add(No);
        No.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        jPanel3.add(No);
        No.setBounds(310, 389, 110, 31);

        isCompulsory.add(yes);
        yes.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        jPanel3.add(yes);
        yes.setBounds(190, 389, 110, 31);

        courseID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        courseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseIDActionPerformed(evt);
            }
        });
        jPanel3.add(courseID);
        courseID.setBounds(190, 308, 230, 30);

        credits.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsActionPerformed(evt);
            }
        });
        jPanel3.add(credits);
        credits.setBounds(190, 269, 230, 30);

        address_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        address_Label.setText("Credits");
        jPanel3.add(address_Label);
        address_Label.setBounds(30, 270, 160, 30);

        fee_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        fee_Label.setText("Fee");
        jPanel3.add(fee_Label);
        fee_Label.setBounds(30, 230, 160, 30);

        fee.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeActionPerformed(evt);
            }
        });
        jPanel3.add(fee);
        fee.setBounds(190, 230, 230, 30);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel3.add(backButton);
        backButton.setBounds(580, 420, 120, 50);

        day_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        day_Label.setText("Day of week");
        jPanel3.add(day_Label);
        day_Label.setBounds(450, 230, 160, 30);

        timeSlot_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        timeSlot_Label.setText("Time Slot");
        jPanel3.add(timeSlot_Label);
        timeSlot_Label.setBounds(450, 270, 160, 30);

        lectureHall_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lectureHall_Label.setText("Lecture Hall");
        jPanel3.add(lectureHall_Label);
        lectureHall_Label.setBounds(450, 310, 160, 30);

        timeSlot.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        timeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotActionPerformed(evt);
            }
        });
        jPanel3.add(timeSlot);
        timeSlot.setBounds(640, 269, 230, 30);

        lectureHall.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lectureHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureHallActionPerformed(evt);
            }
        });
        jPanel3.add(lectureHall);
        lectureHall.setBounds(640, 308, 230, 30);

        dayCombo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        jPanel3.add(dayCombo);
        dayCombo.setBounds(640, 230, 230, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 920, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subjectCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodeActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void semesterIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterIDActionPerformed

    private void lecturerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerIDActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String subject_code = subjectCode.getText();
        String subject_name = name.getText();
        double Fee = Double.parseDouble(fee.getText());
        int Credits = Integer.parseInt(credits.getText());
        String course_id = courseID.getText();
        int semester_id = Integer.parseInt(semesterID.getText());
        String lecturer_id = lecturerID.getText();
        String day_of_week = (String) dayCombo.getSelectedItem();
        String time_slot = timeSlot.getText();
        String lecture_hall = lectureHall.getText();
        String temp = isCompulsory.getSelection().getActionCommand();
        
        boolean is_compulsory;
        if ("Yes".equals(temp))
            is_compulsory = true;
        else
            is_compulsory = false;
        
        subject subj = new subject(subject_code,subject_name,Fee,Credits,course_id,semester_id,lecturer_id,day_of_week,time_slot,lecture_hall,is_compulsory);
        try{
            int result = subjectController.addSubject(subj);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this, "Subject Added Successfully");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Invalid");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        No.setActionCommand("No");
    }//GEN-LAST:event_NoActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        yes.setActionCommand("Yes");
    }//GEN-LAST:event_yesActionPerformed

    private void courseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseIDActionPerformed

    private void creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsActionPerformed

    private void feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void timeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeSlotActionPerformed

    private void lectureHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureHallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectureHallActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton No;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel address_Label;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField courseID;
    private javax.swing.JLabel courseID_Label;
    private javax.swing.JTextField credits;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JLabel day_Label;
    private javax.swing.JTextField fee;
    private javax.swing.JLabel fee_Label;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel home_Label;
    private javax.swing.ButtonGroup isCompulsory;
    private javax.swing.JLabel isCompulsory_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lectureHall;
    private javax.swing.JLabel lectureHall_Label;
    private javax.swing.JTextField lecturerID;
    private javax.swing.JLabel lecturerID_Label;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_Label;
    private javax.swing.JTextField semesterID;
    private javax.swing.JLabel semesterID_Label;
    private javax.swing.JPanel signupHeader;
    private javax.swing.JTextField subjectCode;
    private javax.swing.JLabel subjectCode_Label;
    private javax.swing.JTextField timeSlot;
    private javax.swing.JLabel timeSlot_Label;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
