/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.semesterController;
import Controller.studentSubjectController;
import Controller.subjectController;
import Controller.undergraduateController;
import Model.semester;
import Model.student_subject_semester;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashera
 */
public class edit_enrolled_subjects extends javax.swing.JFrame {
    private final DefaultListModel selectedSubjectListModel =new DefaultListModel();
    private final DefaultListModel selectionSubjectListModel =new DefaultListModel();
    private int semesterid;
    /**
     * Creates new form edit_enrolled_subjects
     */
    public edit_enrolled_subjects() {
        initComponents();
        editSelectionPanel.setVisible(false);
        homeButton.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        semesterNumber = new javax.swing.ButtonGroup();
        editEnrolledSubjectsHeader = new javax.swing.JPanel();
        home_Label = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        getSemester = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        semesterNumber_Label = new javax.swing.JLabel();
        academicYear_Label = new javax.swing.JLabel();
        academicYearCombo = new javax.swing.JComboBox<>();
        semester1 = new javax.swing.JRadioButton();
        semester2 = new javax.swing.JRadioButton();
        studentID_Label = new javax.swing.JLabel();
        getStudentID = new javax.swing.JTextField();
        editSelectionPanel = new javax.swing.JPanel();
        ScrollPane1 = new javax.swing.JScrollPane();
        subjectList = new javax.swing.JList<>();
        addSem1SubjectButton = new javax.swing.JButton();
        removeSem1SubjectButton = new javax.swing.JButton();
        ScrollPane2 = new javax.swing.JScrollPane();
        subjectSelectedList = new javax.swing.JList<>();
        studentID_Label1 = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        semesterID_Label = new javax.swing.JLabel();
        semesterID = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        editEnrolledSubjectsHeader.setBackground(new java.awt.Color(36, 47, 65));
        editEnrolledSubjectsHeader.setLayout(null);

        home_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        editEnrolledSubjectsHeader.add(home_Label);
        home_Label.setBounds(0, 0, 90, 90);

        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        editEnrolledSubjectsHeader.add(homeButton);
        homeButton.setBounds(0, 0, 90, 90);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDIT ENROLLED SUBJECTS");
        editEnrolledSubjectsHeader.add(jLabel1);
        jLabel1.setBounds(0, 13, 900, 64);

        getContentPane().add(editEnrolledSubjectsHeader);
        editEnrolledSubjectsHeader.setBounds(0, 0, 930, 90);

        getSemester.setBackground(new java.awt.Color(97, 212, 195));
        getSemester.setLayout(null);

        confirmButton.setBackground(new java.awt.Color(36, 47, 65));
        confirmButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.setBorder(null);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        confirmButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmButtonKeyPressed(evt);
            }
        });
        getSemester.add(confirmButton);
        confirmButton.setBounds(490, 300, 150, 50);

        backButton1.setBackground(new java.awt.Color(36, 47, 65));
        backButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        getSemester.add(backButton1);
        backButton1.setBounds(300, 300, 150, 50);

        semesterNumber_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semesterNumber_Label.setText("Semester Number");
        getSemester.add(semesterNumber_Label);
        semesterNumber_Label.setBounds(280, 130, 180, 30);

        academicYear_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        academicYear_Label.setText("Academic Year");
        getSemester.add(academicYear_Label);
        academicYear_Label.setBounds(280, 80, 180, 30);

        academicYearCombo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        academicYearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        getSemester.add(academicYearCombo);
        academicYearCombo.setBounds(500, 80, 150, 30);

        semesterNumber.add(semester1);
        semester1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        semester1.setText("1st Semester");
        semester1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester1ActionPerformed(evt);
            }
        });
        getSemester.add(semester1);
        semester1.setBounds(500, 130, 150, 30);

        semesterNumber.add(semester2);
        semester2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        semester2.setText("2nd Semester");
        semester2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester2ActionPerformed(evt);
            }
        });
        getSemester.add(semester2);
        semester2.setBounds(500, 180, 150, 30);

        studentID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        studentID_Label.setText("Student ID");
        getSemester.add(studentID_Label);
        studentID_Label.setBounds(280, 30, 180, 30);

        getStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStudentIDActionPerformed(evt);
            }
        });
        getSemester.add(getStudentID);
        getStudentID.setBounds(500, 30, 150, 30);

        getContentPane().add(getSemester);
        getSemester.setBounds(0, 90, 930, 430);

        editSelectionPanel.setBackground(new java.awt.Color(97, 212, 195));
        editSelectionPanel.setLayout(null);

        ScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        subjectList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        subjectList.setSelectionBackground(new java.awt.Color(36, 47, 65));
        ScrollPane1.setViewportView(subjectList);

        editSelectionPanel.add(ScrollPane1);
        ScrollPane1.setBounds(250, 220, 150, 150);

        addSem1SubjectButton.setBackground(new java.awt.Color(36, 47, 65));
        addSem1SubjectButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        addSem1SubjectButton.setForeground(new java.awt.Color(255, 255, 255));
        addSem1SubjectButton.setText("Add");
        addSem1SubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSem1SubjectButtonActionPerformed(evt);
            }
        });
        editSelectionPanel.add(addSem1SubjectButton);
        addSem1SubjectButton.setBounds(410, 250, 80, 30);

        removeSem1SubjectButton.setBackground(new java.awt.Color(36, 47, 65));
        removeSem1SubjectButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        removeSem1SubjectButton.setForeground(new java.awt.Color(255, 255, 255));
        removeSem1SubjectButton.setText("Remove");
        removeSem1SubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSem1SubjectButtonActionPerformed(evt);
            }
        });
        editSelectionPanel.add(removeSem1SubjectButton);
        removeSem1SubjectButton.setBounds(410, 300, 80, 30);

        ScrollPane2.setBackground(new java.awt.Color(0, 0, 0));

        subjectSelectedList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        subjectSelectedList.setSelectionBackground(new java.awt.Color(36, 47, 65));
        ScrollPane2.setViewportView(subjectSelectedList);

        editSelectionPanel.add(ScrollPane2);
        ScrollPane2.setBounds(500, 220, 150, 150);

        studentID_Label1.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        studentID_Label1.setText("Student ID");
        editSelectionPanel.add(studentID_Label1);
        studentID_Label1.setBounds(40, 140, 160, 30);

        studentID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });
        editSelectionPanel.add(studentID);
        studentID.setBounds(200, 140, 230, 30);

        semesterID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semesterID_Label.setText("Semester ID");
        editSelectionPanel.add(semesterID_Label);
        semesterID_Label.setBounds(450, 140, 160, 30);

        semesterID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        semesterID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterIDActionPerformed(evt);
            }
        });
        editSelectionPanel.add(semesterID);
        semesterID.setBounds(610, 140, 230, 30);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        editSelectionPanel.add(backButton);
        backButton.setBounds(330, 430, 120, 50);

        doneButton.setBackground(new java.awt.Color(36, 47, 65));
        doneButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        editSelectionPanel.add(doneButton);
        doneButton.setBounds(500, 430, 120, 50);

        getContentPane().add(editSelectionPanel);
        editSelectionPanel.setBounds(0, 0, 940, 510);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    //Function to check if current date is 4 weeks before the starting date of the semester given
    public boolean dateValidationForSubjectSelectionEditting(String date1,String date2) throws SQLException {
        try{
            Date d1 = new SimpleDateFormat("yyyy-MM-dd").parse(date1);
            Date d2 = new SimpleDateFormat("yyyy-MM-dd").parse(date2);
            System.out.println(d1+" "+d2);
            GregorianCalendar c1 = new GregorianCalendar(); 
            c1.setTime(d1); 
            GregorianCalendar c2 = new GregorianCalendar(); 
            c2.setTime(d2); 
            for( long i=1; ; i++ ) { 
                    c1.add( Calendar.WEEK_OF_YEAR, 1 ); // add one day, week, year, etc. 
            if( c1.after(c2) ) 
                    return (int)i>=4;
            }
        }catch(ParseException e){
            System.out.println("Oops");
            return false;
        }
    } 
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        String student_id = getStudentID.getText();    
        String academic_year = (String) academicYearCombo.getSelectedItem();
        String semester_number = semesterNumber.getSelection().getActionCommand();
        int year;
        if (null == academic_year)
        year = 4;
        else switch (academic_year) {
            case "1st Year":
            year = 1;
            break;
            case "2nd Year":
            year = 2;
            break;
            case "3rd Year":
            year = 3;
            break;
            default:
            year = 4;
            break;
        }
        semester sem = new semester(year, Integer.parseInt(semester_number));
        try {
            ResultSet rs = undergraduateController.checkStudentID(student_id);
            if (rs.next()) {
                semesterid = semesterController.findSemesterID(sem);
                ArrayList<String> list = studentSubjectController.getSelectedSubjectList(student_id, semesterid);
                if (list.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Not Enrolled");
                    getStudentID.setText(null);
                }
                else{
                    //Checking if the current date is 4 weeks before the semester start date
                    String currentDate = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
                    String sem_start_date = semesterController.getSemesterStartDate("SCS",semesterid);
                    if(dateValidationForSubjectSelectionEditting(currentDate,sem_start_date)){
                        JOptionPane.showMessageDialog(this, "Allowed to Edit");
                        
                         //Setting the subjects to be selected from
                        ArrayList<String> selectionSubjectList = subjectController.getSubjects("SCS",semesterid,false);
                        for (String subject : selectionSubjectList) {
                            selectionSubjectListModel.addElement(subject);
                        }
                        subjectList.setModel(selectionSubjectListModel);

                        getSemester.setVisible(false);
                        editSelectionPanel.setVisible(true);
                        studentID.setEditable(false);
                        studentID.setText(student_id);
                        semesterID.setEditable(false);
                        semesterID.setText(Integer.toString(semesterid));
                        for (String subject : list) {
                            selectedSubjectListModel.addElement(subject);
                            selectionSubjectListModel.remove(selectionSubjectListModel.indexOf(subject));
                            subjectList.setModel(selectionSubjectListModel);
                        }
                        subjectSelectedList.setModel(selectedSubjectListModel);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Not Allowed to Edit! Redirecting to Homepage");
                        new homepage().setVisible(true);
                        this.dispose();
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Student Not Found");
                getStudentID.setText(null);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void confirmButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonKeyPressed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        new manage_subject().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void semester1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester1ActionPerformed
        semester1.setActionCommand("1");
    }//GEN-LAST:event_semester1ActionPerformed

    private void semester2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester2ActionPerformed
        semester2.setActionCommand("2");
    }//GEN-LAST:event_semester2ActionPerformed

    private void getStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getStudentIDActionPerformed

    private void addSem1SubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSem1SubjectButtonActionPerformed
        if(subjectList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this,"No Subject Selected");
        }
        else {
            if(selectedSubjectListModel.size()<4) {
                selectedSubjectListModel.addElement(subjectList.getSelectedValue());
                selectionSubjectListModel.remove(subjectList.getSelectedIndex());
                subjectList.setModel(selectionSubjectListModel);
                subjectSelectedList.setModel(selectedSubjectListModel);
            }
            else {
                JOptionPane.showMessageDialog(this, "Subject Limit Reached");
            }
        }
    }//GEN-LAST:event_addSem1SubjectButtonActionPerformed

    private void removeSem1SubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSem1SubjectButtonActionPerformed
        if(subjectSelectedList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this,"No Subject Selected");
        }
        else {
            selectionSubjectListModel.addElement(subjectSelectedList.getSelectedValue());
            selectedSubjectListModel.remove(subjectSelectedList.getSelectedIndex());
            subjectList.setModel(selectionSubjectListModel);
            subjectSelectedList.setModel(selectedSubjectListModel);
        }
    }//GEN-LAST:event_removeSem1SubjectButtonActionPerformed

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDActionPerformed

    private void semesterIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterIDActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        String ID = getStudentID.getText();
        
        try{
            int result = studentSubjectController.deleteSelection(ID, semesterid);
            if ( result>0 ) {
                System.out.println("Deletion Successful");
            }else {
                System.out.println("Deletion Unsuccessful");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
        int size = subjectSelectedList.getModel().getSize();
        ArrayList<String> newlySelectedList = new ArrayList<>();
        
        try {
            newlySelectedList = subjectController.getCompulsorySubjects("SCS",semesterid,true);
            for (String compulsorySubject:newlySelectedList) {
                student_subject_semester addsubject = new student_subject_semester(ID,compulsorySubject,semesterid);
                studentSubjectController.addStudentSubject(addsubject);
            }
        } catch (SQLException ex) {
            Logger.getLogger(subject_selection.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i=0;i<size;i++) {
            String subject_code;
            try {
                subject_code = subjectController.getSubjectCode(subjectSelectedList.getModel().getElementAt(i));
                student_subject_semester addsubject = new student_subject_semester(ID,subject_code,semesterid);
                studentSubjectController.addStudentSubject(addsubject);
            } catch (SQLException ex) {
                Logger.getLogger(subject_selection.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }  
        JOptionPane.showMessageDialog(this,"Successfully Updated Subjects");
        new homepage().setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_doneButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_enrolled_subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_enrolled_subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_enrolled_subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_enrolled_subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_enrolled_subjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane2;
    private javax.swing.JComboBox<String> academicYearCombo;
    private javax.swing.JLabel academicYear_Label;
    private javax.swing.JButton addSem1SubjectButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JPanel editEnrolledSubjectsHeader;
    private javax.swing.JPanel editSelectionPanel;
    private javax.swing.JPanel getSemester;
    private javax.swing.JTextField getStudentID;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel home_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeSem1SubjectButton;
    private javax.swing.JRadioButton semester1;
    private javax.swing.JRadioButton semester2;
    private javax.swing.JTextField semesterID;
    private javax.swing.JLabel semesterID_Label;
    private javax.swing.ButtonGroup semesterNumber;
    private javax.swing.JLabel semesterNumber_Label;
    private javax.swing.JTextField studentID;
    private javax.swing.JLabel studentID_Label;
    private javax.swing.JLabel studentID_Label1;
    private javax.swing.JList<String> subjectList;
    private javax.swing.JList<String> subjectSelectedList;
    // End of variables declaration//GEN-END:variables
}
