/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.labController;
import Model.lab;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashera
 */
public class edit_assigned_lab extends javax.swing.JFrame {

    /**
     * Creates new form edit_assigned_lab
     */
    public edit_assigned_lab() {
        initComponents();
        editAssignedLabPanel.setVisible(false);
        homeButton1.setContentAreaFilled(false);
        homeButton.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getTimeSlotPanel = new javax.swing.JPanel();
        manageLabAssignmentHeader = new javax.swing.JPanel();
        editLabAssignmentLabel = new javax.swing.JLabel();
        home_Label = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        day_Label = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        time_Label = new javax.swing.JLabel();
        labCode_Label = new javax.swing.JLabel();
        dayCombo1 = new javax.swing.JComboBox<>();
        timeCombo1 = new javax.swing.JComboBox<>();
        labCode1 = new javax.swing.JTextField();
        editAssignedLabPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home_Label1 = new javax.swing.JLabel();
        homeButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        subjectCode_label = new javax.swing.JLabel();
        instructor_id_label = new javax.swing.JLabel();
        labCode_label = new javax.swing.JLabel();
        day_Label1 = new javax.swing.JLabel();
        timeSlot_Label = new javax.swing.JLabel();
        studentRange_label = new javax.swing.JLabel();
        studentRange = new javax.swing.JTextField();
        labCode = new javax.swing.JTextField();
        instructorID = new javax.swing.JTextField();
        subjectCode = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        time = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        getTimeSlotPanel.setBackground(new java.awt.Color(97, 212, 195));
        getTimeSlotPanel.setLayout(null);

        manageLabAssignmentHeader.setBackground(new java.awt.Color(36, 47, 65));
        manageLabAssignmentHeader.setLayout(null);

        editLabAssignmentLabel.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        editLabAssignmentLabel.setForeground(new java.awt.Color(255, 255, 255));
        editLabAssignmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editLabAssignmentLabel.setText("EDIT LAB ASSIGNMENT");
        manageLabAssignmentHeader.add(editLabAssignmentLabel);
        editLabAssignmentLabel.setBounds(0, 13, 900, 64);

        home_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        manageLabAssignmentHeader.add(home_Label);
        home_Label.setBounds(0, 0, 90, 90);

        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        manageLabAssignmentHeader.add(homeButton);
        homeButton.setBounds(0, 0, 90, 90);

        getTimeSlotPanel.add(manageLabAssignmentHeader);
        manageLabAssignmentHeader.setBounds(0, 0, 930, 90);

        day_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        day_Label.setText("Day of Week");
        getTimeSlotPanel.add(day_Label);
        day_Label.setBounds(250, 150, 180, 30);

        confirmButton.setBackground(new java.awt.Color(36, 47, 65));
        confirmButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.setBorder(null);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        confirmButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmButtonKeyPressed(evt);
            }
        });
        getTimeSlotPanel.add(confirmButton);
        confirmButton.setBounds(490, 350, 150, 50);

        backButton1.setBackground(new java.awt.Color(36, 47, 65));
        backButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        getTimeSlotPanel.add(backButton1);
        backButton1.setBounds(300, 350, 150, 50);

        time_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        time_Label.setText("Time Slot");
        getTimeSlotPanel.add(time_Label);
        time_Label.setBounds(250, 200, 180, 30);

        labCode_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        labCode_Label.setText("Lab Code");
        getTimeSlotPanel.add(labCode_Label);
        labCode_Label.setBounds(250, 250, 180, 30);

        dayCombo1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        dayCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        getTimeSlotPanel.add(dayCombo1);
        dayCombo1.setBounds(490, 150, 195, 30);

        timeCombo1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        timeCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8.00-10.00", "10.00-12.00", "1.00-3.00" }));
        getTimeSlotPanel.add(timeCombo1);
        timeCombo1.setBounds(490, 200, 195, 30);

        labCode1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        labCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labCode1ActionPerformed(evt);
            }
        });
        getTimeSlotPanel.add(labCode1);
        labCode1.setBounds(490, 250, 180, 30);

        getContentPane().add(getTimeSlotPanel);
        getTimeSlotPanel.setBounds(0, 0, 940, 520);

        editAssignedLabPanel.setBackground(new java.awt.Color(97, 212, 195));
        editAssignedLabPanel.setLayout(null);

        Header.setBackground(new java.awt.Color(36, 47, 65));
        Header.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDIT LAB ASSIGNMENT");
        Header.add(jLabel1);
        jLabel1.setBounds(0, 13, 900, 64);

        home_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        Header.add(home_Label1);
        home_Label1.setBounds(0, 0, 90, 90);

        homeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton1ActionPerformed(evt);
            }
        });
        Header.add(homeButton1);
        homeButton1.setBounds(0, 0, 90, 90);

        editAssignedLabPanel.add(Header);
        Header.setBounds(0, 0, 930, 90);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(backButton);
        backButton.setBounds(220, 430, 150, 50);

        updateButton.setBackground(new java.awt.Color(36, 47, 65));
        updateButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(updateButton);
        updateButton.setBounds(390, 430, 150, 50);

        deleteButton.setBackground(new java.awt.Color(36, 47, 65));
        deleteButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(deleteButton);
        deleteButton.setBounds(560, 430, 150, 50);

        subjectCode_label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        subjectCode_label.setText("Subject Code");
        editAssignedLabPanel.add(subjectCode_label);
        subjectCode_label.setBounds(220, 130, 160, 30);

        instructor_id_label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        instructor_id_label.setText("Instructor ID");
        editAssignedLabPanel.add(instructor_id_label);
        instructor_id_label.setBounds(220, 170, 160, 30);

        labCode_label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        labCode_label.setText("Lab Code (Fixed)");
        editAssignedLabPanel.add(labCode_label);
        labCode_label.setBounds(220, 210, 250, 30);

        day_Label1.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        day_Label1.setText("Day of week (Fixed) ");
        editAssignedLabPanel.add(day_Label1);
        day_Label1.setBounds(220, 250, 250, 30);

        timeSlot_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        timeSlot_Label.setText("Time Slot (Fixed)");
        editAssignedLabPanel.add(timeSlot_Label);
        timeSlot_Label.setBounds(220, 290, 250, 30);

        studentRange_label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        studentRange_label.setText("Student Range");
        editAssignedLabPanel.add(studentRange_label);
        studentRange_label.setBounds(220, 330, 160, 30);

        studentRange.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        studentRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRangeActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(studentRange);
        studentRange.setBounds(470, 330, 250, 30);

        labCode.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        labCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labCodeActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(labCode);
        labCode.setBounds(470, 210, 250, 30);

        instructorID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        instructorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorIDActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(instructorID);
        instructorID.setBounds(470, 170, 250, 30);

        subjectCode.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        subjectCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCodeActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(subjectCode);
        subjectCode.setBounds(470, 130, 250, 30);

        day.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(day);
        day.setBounds(470, 250, 250, 30);

        time.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        editAssignedLabPanel.add(time);
        time.setBounds(470, 290, 250, 30);

        getContentPane().add(editAssignedLabPanel);
        editAssignedLabPanel.setBounds(0, 0, 920, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new manage_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String subject_code = subjectCode.getText();
        String instructor_id = instructorID.getText();
        String lab_code = labCode.getText();
        String day_of_week = day.getText();
        String time_slot = time.getText();
        String student_list = studentRange.getText();

        lab labSession = new lab(day_of_week,time_slot,lab_code,subject_code,instructor_id,student_list);
        try{
            int result = labController.updateLabSession(labSession);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this, "Successfully Updated");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Update Failed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String day_of_week = day.getText();
        String time_slot = time.getText();
        String lab_code = labCode.getText();
        try{
            int result = labController.deleteLabSession(day_of_week,time_slot,lab_code);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this, "Successfully Deleted");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Delete Failed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        String day_of_week = (String) dayCombo1.getSelectedItem();
        String time_slot = (String) timeCombo1.getSelectedItem();
        String lab_code = labCode1.getText();
        try {
            lab labSession = labController.searchLabSession(day_of_week,time_slot,lab_code);
            if (labSession!=null) {
                getTimeSlotPanel.setVisible(false);
                editAssignedLabPanel.setVisible(true);
                
                //Pre-setting the primary key fields to be unedittable
                labCode.setEditable(false);
                day.setEditable(false);
                time.setEditable(false);
                
                subjectCode.setText(labSession.getSubject_code());
                instructorID.setText(labSession.getInstructor_id());
                labCode.setText(labSession.getLab_code());
                day.setText(labSession.getDay_of_week());
                time.setText(labSession.getTime_slot());
                studentRange.setText(labSession.getStudent_list());
            }else{
                JOptionPane.showMessageDialog(this, "Lab Session Not Found");
                labCode1.setText(null);
            }
        } catch (SQLException ex) {
            Logger.getLogger(manage_lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void confirmButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonKeyPressed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        new manage_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void homeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton1ActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButton1ActionPerformed

    private void labCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labCode1ActionPerformed

    private void studentRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentRangeActionPerformed

    private void labCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labCodeActionPerformed

    private void instructorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorIDActionPerformed

    private void subjectCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodeActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_assigned_lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_assigned_lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_assigned_lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_assigned_lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_assigned_lab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField day;
    private javax.swing.JComboBox<String> dayCombo1;
    private javax.swing.JLabel day_Label;
    private javax.swing.JLabel day_Label1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel editAssignedLabPanel;
    private javax.swing.JLabel editLabAssignmentLabel;
    private javax.swing.JPanel getTimeSlotPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton homeButton1;
    private javax.swing.JLabel home_Label;
    private javax.swing.JLabel home_Label1;
    private javax.swing.JTextField instructorID;
    private javax.swing.JLabel instructor_id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField labCode;
    private javax.swing.JTextField labCode1;
    private javax.swing.JLabel labCode_Label;
    private javax.swing.JLabel labCode_label;
    private javax.swing.JPanel manageLabAssignmentHeader;
    private javax.swing.JTextField studentRange;
    private javax.swing.JLabel studentRange_label;
    private javax.swing.JTextField subjectCode;
    private javax.swing.JLabel subjectCode_label;
    private javax.swing.JTextField time;
    private javax.swing.JComboBox<String> timeCombo1;
    private javax.swing.JLabel timeSlot_Label;
    private javax.swing.JLabel time_Label;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
