/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

/**
 *
 * @author Ashera
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupHeader = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        header_label = new javax.swing.JLabel();
        addStudentImg = new javax.swing.JLabel();
        addStudentButton = new javax.swing.JButton();
        addStaffImg = new javax.swing.JLabel();
        addStaffButton = new javax.swing.JButton();
        manageStudentImg = new javax.swing.JLabel();
        manageStudentButton = new javax.swing.JButton();
        manageStaffImg = new javax.swing.JLabel();
        manageStaffButton = new javax.swing.JButton();
        addSubjectImg = new javax.swing.JLabel();
        addSubjectButton = new javax.swing.JButton();
        manageSubjectImg = new javax.swing.JLabel();
        manageSubjectButton = new javax.swing.JButton();
        addSubjectImg1 = new javax.swing.JLabel();
        paymentButton = new javax.swing.JButton();
        manageSubjectImg1 = new javax.swing.JLabel();
        resultButton = new javax.swing.JButton();
        backgroundImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        signupHeader.setBackground(new java.awt.Color(36, 47, 65));
        signupHeader.setLayout(null);

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(36, 47, 65));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        signupHeader.add(logoutButton);
        logoutButton.setBounds(770, 30, 100, 30);

        header_label.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        header_label.setForeground(new java.awt.Color(255, 255, 255));
        header_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_label.setText("HOME");
        signupHeader.add(header_label);
        header_label.setBounds(0, 13, 900, 64);

        getContentPane().add(signupHeader);
        signupHeader.setBounds(0, 0, 920, 90);

        addStudentImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addStudentImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/students.png"))); // NOI18N
        getContentPane().add(addStudentImg);
        addStudentImg.setBounds(30, 120, 130, 130);

        addStudentButton.setBackground(new java.awt.Color(255, 255, 255));
        addStudentButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(36, 47, 65));
        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addStudentButton);
        addStudentButton.setBounds(30, 260, 130, 30);

        addStaffImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addStaffImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/academicStaff.png"))); // NOI18N
        getContentPane().add(addStaffImg);
        addStaffImg.setBounds(270, 120, 130, 130);

        addStaffButton.setBackground(new java.awt.Color(255, 255, 255));
        addStaffButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addStaffButton.setForeground(new java.awt.Color(36, 47, 65));
        addStaffButton.setText("Add Staff");
        addStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addStaffButton);
        addStaffButton.setBounds(270, 260, 130, 30);

        manageStudentImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageStudentImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageStudent.png"))); // NOI18N
        getContentPane().add(manageStudentImg);
        manageStudentImg.setBounds(30, 300, 130, 130);

        manageStudentButton.setBackground(new java.awt.Color(255, 255, 255));
        manageStudentButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        manageStudentButton.setForeground(new java.awt.Color(36, 47, 65));
        manageStudentButton.setText("Manage Student");
        manageStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageStudentButton);
        manageStudentButton.setBounds(20, 440, 150, 30);

        manageStaffImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageStaffImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageStaff.png"))); // NOI18N
        getContentPane().add(manageStaffImg);
        manageStaffImg.setBounds(270, 300, 130, 130);

        manageStaffButton.setBackground(new java.awt.Color(255, 255, 255));
        manageStaffButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        manageStaffButton.setForeground(new java.awt.Color(36, 47, 65));
        manageStaffButton.setText("Manage Staff");
        manageStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStaffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageStaffButton);
        manageStaffButton.setBounds(260, 440, 150, 30);

        addSubjectImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addSubjectImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/subject.png"))); // NOI18N
        getContentPane().add(addSubjectImg);
        addSubjectImg.setBounds(510, 120, 130, 130);

        addSubjectButton.setBackground(new java.awt.Color(255, 255, 255));
        addSubjectButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addSubjectButton.setForeground(new java.awt.Color(36, 47, 65));
        addSubjectButton.setText("Add Subject");
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addSubjectButton);
        addSubjectButton.setBounds(510, 260, 130, 30);

        manageSubjectImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageSubjectImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editSubject.png"))); // NOI18N
        getContentPane().add(manageSubjectImg);
        manageSubjectImg.setBounds(510, 300, 130, 130);

        manageSubjectButton.setBackground(new java.awt.Color(255, 255, 255));
        manageSubjectButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        manageSubjectButton.setForeground(new java.awt.Color(36, 47, 65));
        manageSubjectButton.setText("Manage Subject");
        manageSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSubjectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageSubjectButton);
        manageSubjectButton.setBounds(500, 440, 150, 30);

        addSubjectImg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addSubjectImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money.png"))); // NOI18N
        getContentPane().add(addSubjectImg1);
        addSubjectImg1.setBounds(750, 120, 130, 130);

        paymentButton.setBackground(new java.awt.Color(255, 255, 255));
        paymentButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(36, 47, 65));
        paymentButton.setText("Payment");
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(paymentButton);
        paymentButton.setBounds(750, 260, 130, 30);

        manageSubjectImg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageSubjectImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/test.png"))); // NOI18N
        getContentPane().add(manageSubjectImg1);
        manageSubjectImg1.setBounds(750, 300, 130, 130);

        resultButton.setBackground(new java.awt.Color(255, 255, 255));
        resultButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        resultButton.setForeground(new java.awt.Color(36, 47, 65));
        resultButton.setText("Examination");
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resultButton);
        resultButton.setBounds(750, 440, 130, 30);

        backgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(backgroundImg);
        backgroundImg.setBounds(0, 0, 950, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new main_NSBM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffButtonActionPerformed
        new staff_registration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addStaffButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        new student_registration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void manageStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentButtonActionPerformed
        new manage_student().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageStudentButtonActionPerformed

    private void manageStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStaffButtonActionPerformed
        new manage_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageStaffButtonActionPerformed

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        new add_subject().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    private void manageSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSubjectButtonActionPerformed
        new manage_subject().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageSubjectButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        new payment_details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        new manage_results().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffButton;
    private javax.swing.JLabel addStaffImg;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JLabel addStudentImg;
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JLabel addSubjectImg;
    private javax.swing.JLabel addSubjectImg1;
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JLabel header_label;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageStaffButton;
    private javax.swing.JLabel manageStaffImg;
    private javax.swing.JButton manageStudentButton;
    private javax.swing.JLabel manageStudentImg;
    private javax.swing.JButton manageSubjectButton;
    private javax.swing.JLabel manageSubjectImg;
    private javax.swing.JLabel manageSubjectImg1;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton resultButton;
    private javax.swing.JPanel signupHeader;
    // End of variables declaration//GEN-END:variables
}
