/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.lecturerController;
import Model.lecturer;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashera
 */
public class manage_lecturer extends javax.swing.JFrame {

    /**
     * Creates new form edit_lecturer
     */
    public manage_lecturer() {
        initComponents();
        manageLecturerPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        getLecturerIDPanel = new javax.swing.JPanel();
        manageLecturerHeader = new javax.swing.JPanel();
        manageLecturerLabel = new javax.swing.JLabel();
        lectuerid_Label = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        lecturerid = new javax.swing.JTextField();
        manageLecturerPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lecturerID_Label = new javax.swing.JLabel();
        name_Label = new javax.swing.JLabel();
        nic_Label = new javax.swing.JLabel();
        roomNumber_Label = new javax.swing.JLabel();
        contactNumber_Label = new javax.swing.JLabel();
        lecturerID = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        roomNumber = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        email_Label = new javax.swing.JLabel();
        address_Label = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        gender_Label = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        getLecturerIDPanel.setBackground(new java.awt.Color(97, 212, 195));
        getLecturerIDPanel.setLayout(null);

        manageLecturerHeader.setBackground(new java.awt.Color(36, 47, 65));
        manageLecturerHeader.setLayout(null);

        manageLecturerLabel.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        manageLecturerLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageLecturerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageLecturerLabel.setText("MANAGE LECTURER");
        manageLecturerHeader.add(manageLecturerLabel);
        manageLecturerLabel.setBounds(0, 13, 900, 64);

        getLecturerIDPanel.add(manageLecturerHeader);
        manageLecturerHeader.setBounds(0, 0, 930, 90);

        lectuerid_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lectuerid_Label.setText("Lecturer ID");
        getLecturerIDPanel.add(lectuerid_Label);
        lectuerid_Label.setBounds(280, 190, 180, 30);

        confirmButton.setBackground(new java.awt.Color(36, 47, 65));
        confirmButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.setBorder(null);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        confirmButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmButtonKeyPressed(evt);
            }
        });
        getLecturerIDPanel.add(confirmButton);
        confirmButton.setBounds(490, 300, 150, 50);

        backButton1.setBackground(new java.awt.Color(36, 47, 65));
        backButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        getLecturerIDPanel.add(backButton1);
        backButton1.setBounds(300, 300, 150, 50);

        lecturerid.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lecturerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureridActionPerformed(evt);
            }
        });
        getLecturerIDPanel.add(lecturerid);
        lecturerid.setBounds(500, 190, 150, 30);

        getContentPane().add(getLecturerIDPanel);
        getLecturerIDPanel.setBounds(0, 0, 940, 520);

        manageLecturerPanel.setBackground(new java.awt.Color(97, 212, 195));
        manageLecturerPanel.setLayout(null);

        Header.setBackground(new java.awt.Color(36, 47, 65));
        Header.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE LECTURER");
        Header.add(jLabel1);
        jLabel1.setBounds(0, 13, 900, 64);

        manageLecturerPanel.add(Header);
        Header.setBounds(0, 0, 930, 90);

        lecturerID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lecturerID_Label.setText("Lecturer ID");
        manageLecturerPanel.add(lecturerID_Label);
        lecturerID_Label.setBounds(230, 100, 160, 30);

        name_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        name_Label.setText("Name");
        manageLecturerPanel.add(name_Label);
        name_Label.setBounds(230, 140, 160, 30);

        nic_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        nic_Label.setText("NIC");
        manageLecturerPanel.add(nic_Label);
        nic_Label.setBounds(230, 260, 160, 30);

        roomNumber_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        roomNumber_Label.setText("Room Number");
        manageLecturerPanel.add(roomNumber_Label);
        roomNumber_Label.setBounds(230, 340, 180, 30);

        contactNumber_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        contactNumber_Label.setText("Contact Number");
        manageLecturerPanel.add(contactNumber_Label);
        contactNumber_Label.setBounds(230, 300, 180, 30);

        lecturerID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lecturerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerIDActionPerformed(evt);
            }
        });
        lecturerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lecturerIDKeyPressed(evt);
            }
        });
        manageLecturerPanel.add(lecturerID);
        lecturerID.setBounds(420, 100, 280, 30);

        name.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(name);
        name.setBounds(420, 140, 280, 30);

        roomNumber.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        roomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(roomNumber);
        roomNumber.setBounds(420, 340, 280, 30);

        contactNumber.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        contactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(contactNumber);
        contactNumber.setBounds(420, 300, 280, 30);

        nic.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(nic);
        nic.setBounds(420, 260, 280, 30);

        email.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(email);
        email.setBounds(420, 220, 280, 30);

        email_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        email_Label.setText("Email");
        manageLecturerPanel.add(email_Label);
        email_Label.setBounds(230, 220, 160, 30);

        address_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        address_Label.setText("Address");
        manageLecturerPanel.add(address_Label);
        address_Label.setBounds(230, 180, 160, 30);

        address.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(address);
        address.setBounds(420, 180, 280, 30);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(backButton);
        backButton.setBounds(220, 430, 150, 50);

        gender_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        gender_Label.setText("Gender");
        manageLecturerPanel.add(gender_Label);
        gender_Label.setBounds(230, 380, 160, 30);

        gender.add(male);
        male.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(male);
        male.setBounds(420, 380, 130, 31);

        gender.add(female);
        female.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(female);
        female.setBounds(570, 380, 130, 31);

        updateButton.setBackground(new java.awt.Color(36, 47, 65));
        updateButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(updateButton);
        updateButton.setBounds(390, 430, 150, 50);

        deleteButton.setBackground(new java.awt.Color(36, 47, 65));
        deleteButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        manageLecturerPanel.add(deleteButton);
        deleteButton.setBounds(560, 430, 150, 50);

        getContentPane().add(manageLecturerPanel);
        manageLecturerPanel.setBounds(0, 0, 920, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lecturerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerIDActionPerformed
     
    }//GEN-LAST:event_lecturerIDActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void roomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberActionPerformed

    private void contactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new manage_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        male.setActionCommand("Male");
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        female.setActionCommand("Female");
    }//GEN-LAST:event_femaleActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String Lecturer_id = lecturerID.getText();
        String Name = name.getText();
        String Address = address.getText();
        String Gender = gender.getSelection().getActionCommand();
        String Email = email.getText();
        String NIC = nic.getText();
        String Contact_number = contactNumber.getText();
        int Room_number = Integer.parseInt(roomNumber.getText());
        
        lecturer Lecturer = new lecturer(Lecturer_id,Name,Address,Gender,Email,NIC,Contact_number,Room_number);
        try{
            int result = lecturerController.updateLecturer(Lecturer);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this, "Successfully Updated");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Update Failed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void lecturerIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lecturerIDKeyPressed

    }//GEN-LAST:event_lecturerIDKeyPressed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String Lecturer_id = lecturerID.getText();

        try{
            int result = lecturerController.deleteLecturer(Lecturer_id);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this, "Successfully Deleted");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Delete Failed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
            String Lecturer_id = lecturerid.getText();
            lecturerID.setEditable(false);
            try {
                lecturer Lecturer = lecturerController.searchLecturer(Lecturer_id);
                if (Lecturer!=null) {
                    getLecturerIDPanel.setVisible(false);
                    manageLecturerPanel.setVisible(true);
                    lecturerID.setText(Lecturer.getLecturer_id());
                    name.setText(Lecturer.getName());
                    address.setText(Lecturer.getAddress());
                    String Gender = Lecturer.getGender();
                    if ("Male".equals(Gender)){
                        male.setSelected(true);
                        male.setActionCommand("Male");
                    }
                    else{
                        female.setSelected(true);
                        female.setActionCommand("Female");
                    }
                    email.setText(Lecturer.getEmail());
                    nic.setText(Lecturer.getNic());
                    contactNumber.setText(Lecturer.getContact_number());
                    roomNumber.setText(Integer.toString(Lecturer.getRoom_number()));
                }else{
                    JOptionPane.showMessageDialog(this, "Lecturer Not Found");
                    lecturerid.setText(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(manage_lecturer.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void confirmButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonKeyPressed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        new manage_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void lectureridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectureridActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_lecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JTextField address;
    private javax.swing.JLabel address_Label;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JLabel contactNumber_Label;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_Label;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel gender_Label;
    private javax.swing.JPanel getLecturerIDPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lectuerid_Label;
    private javax.swing.JTextField lecturerID;
    private javax.swing.JLabel lecturerID_Label;
    private javax.swing.JTextField lecturerid;
    private javax.swing.JRadioButton male;
    private javax.swing.JPanel manageLecturerHeader;
    private javax.swing.JLabel manageLecturerLabel;
    private javax.swing.JPanel manageLecturerPanel;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_Label;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel nic_Label;
    private javax.swing.JTextField roomNumber;
    private javax.swing.JLabel roomNumber_Label;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
