/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.instructorController;
import Model.instructor;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashera
 */
public class manage_instructor extends javax.swing.JFrame {

    /**
     * Creates new form edit_instructor
     */
    public manage_instructor() {
        initComponents();
        manageInstructorPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        getInstructorIDPanel = new javax.swing.JPanel();
        manageLecturerHeader = new javax.swing.JPanel();
        manageInstructorLabel = new javax.swing.JLabel();
        instructorid_Label = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        instructorid = new javax.swing.JTextField();
        manageInstructorPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        manageInstructor_Label = new javax.swing.JLabel();
        instructorID_Label = new javax.swing.JLabel();
        name_Label = new javax.swing.JLabel();
        nic_Label = new javax.swing.JLabel();
        contactNumber_Label = new javax.swing.JLabel();
        instructorID = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        email_Label = new javax.swing.JLabel();
        address_Label = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        gender_Label = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        getInstructorIDPanel.setBackground(new java.awt.Color(97, 212, 195));
        getInstructorIDPanel.setLayout(null);

        manageLecturerHeader.setBackground(new java.awt.Color(36, 47, 65));
        manageLecturerHeader.setLayout(null);

        manageInstructorLabel.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        manageInstructorLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageInstructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageInstructorLabel.setText("MANAGE INSTRUCTOR");
        manageLecturerHeader.add(manageInstructorLabel);
        manageInstructorLabel.setBounds(0, 13, 900, 64);

        getInstructorIDPanel.add(manageLecturerHeader);
        manageLecturerHeader.setBounds(0, 0, 930, 90);

        instructorid_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        instructorid_Label.setText("Instructor ID");
        getInstructorIDPanel.add(instructorid_Label);
        instructorid_Label.setBounds(280, 190, 180, 30);

        confirmButton.setBackground(new java.awt.Color(36, 47, 65));
        confirmButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.setBorder(null);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        confirmButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmButtonKeyPressed(evt);
            }
        });
        getInstructorIDPanel.add(confirmButton);
        confirmButton.setBounds(490, 300, 150, 50);

        backButton1.setBackground(new java.awt.Color(36, 47, 65));
        backButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        getInstructorIDPanel.add(backButton1);
        backButton1.setBounds(300, 300, 150, 50);

        instructorid.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        instructorid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructoridActionPerformed(evt);
            }
        });
        getInstructorIDPanel.add(instructorid);
        instructorid.setBounds(500, 190, 150, 30);

        getContentPane().add(getInstructorIDPanel);
        getInstructorIDPanel.setBounds(0, 0, 940, 520);

        manageInstructorPanel.setBackground(new java.awt.Color(97, 212, 195));
        manageInstructorPanel.setLayout(null);

        Header.setBackground(new java.awt.Color(36, 47, 65));
        Header.setLayout(null);

        manageInstructor_Label.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        manageInstructor_Label.setForeground(new java.awt.Color(255, 255, 255));
        manageInstructor_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageInstructor_Label.setText("MANAGE INSTRUCTOR");
        Header.add(manageInstructor_Label);
        manageInstructor_Label.setBounds(0, 13, 920, 64);

        manageInstructorPanel.add(Header);
        Header.setBounds(0, 0, 930, 90);

        instructorID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        instructorID_Label.setText("Instructor ID");
        manageInstructorPanel.add(instructorID_Label);
        instructorID_Label.setBounds(230, 120, 160, 30);

        name_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        name_Label.setText("Name");
        manageInstructorPanel.add(name_Label);
        name_Label.setBounds(230, 160, 160, 30);

        nic_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        nic_Label.setText("NIC");
        manageInstructorPanel.add(nic_Label);
        nic_Label.setBounds(230, 280, 160, 30);

        contactNumber_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        contactNumber_Label.setText("Contact Number");
        manageInstructorPanel.add(contactNumber_Label);
        contactNumber_Label.setBounds(230, 320, 180, 30);

        instructorID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        instructorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorIDActionPerformed(evt);
            }
        });
        instructorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                instructorIDKeyPressed(evt);
            }
        });
        manageInstructorPanel.add(instructorID);
        instructorID.setBounds(420, 120, 280, 30);

        name.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(name);
        name.setBounds(420, 160, 280, 30);

        contactNumber.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        contactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(contactNumber);
        contactNumber.setBounds(420, 320, 280, 30);

        nic.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(nic);
        nic.setBounds(420, 280, 280, 30);

        email.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(email);
        email.setBounds(420, 240, 280, 30);

        email_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        email_Label.setText("Email");
        manageInstructorPanel.add(email_Label);
        email_Label.setBounds(230, 240, 160, 30);

        address_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        address_Label.setText("Address");
        manageInstructorPanel.add(address_Label);
        address_Label.setBounds(230, 200, 160, 30);

        address.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(address);
        address.setBounds(420, 200, 280, 30);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(backButton);
        backButton.setBounds(220, 430, 150, 50);

        gender_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        gender_Label.setText("Gender");
        manageInstructorPanel.add(gender_Label);
        gender_Label.setBounds(230, 360, 160, 30);

        gender.add(male);
        male.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(male);
        male.setBounds(420, 360, 130, 31);

        gender.add(female);
        female.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(female);
        female.setBounds(570, 360, 130, 31);

        updateButton.setBackground(new java.awt.Color(36, 47, 65));
        updateButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(updateButton);
        updateButton.setBounds(390, 430, 150, 50);

        deleteButton.setBackground(new java.awt.Color(36, 47, 65));
        deleteButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        manageInstructorPanel.add(deleteButton);
        deleteButton.setBounds(560, 430, 150, 50);

        getContentPane().add(manageInstructorPanel);
        manageInstructorPanel.setBounds(0, 0, 920, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void instructorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorIDActionPerformed

    }//GEN-LAST:event_instructorIDActionPerformed

    private void instructorIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instructorIDKeyPressed

    }//GEN-LAST:event_instructorIDKeyPressed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void contactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new manage_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        male.setActionCommand("Male");
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        female.setActionCommand("Female");
    }//GEN-LAST:event_femaleActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String Instructor_id = instructorID.getText();
        String Name = name.getText();
        String Address = address.getText();
        String Gender = gender.getSelection().getActionCommand();
        String Email = email.getText();
        String NIC = nic.getText();
        String Contact_number = contactNumber.getText();

        instructor Instructor = new instructor(Instructor_id,Name,Address,Gender,Email,NIC,Contact_number);
        try{
            int result = instructorController.updateInstructor(Instructor);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this, "Successfully Updated");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Update Failed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String Instructor_id = instructorID.getText();

        try{
            int result = instructorController.deleteInstructor(Instructor_id);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this, "Successfully Deleted");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Delete Failed");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
    String Instructor_id = instructorid.getText();
    instructorID.setEditable(false);
    try {
        instructor Instructor = instructorController.searchInstructor(Instructor_id);
        if (Instructor!=null) {
            getInstructorIDPanel.setVisible(false);
            manageInstructorPanel.setVisible(true);
            instructorID.setText(Instructor.getInstructor_id());
            name.setText(Instructor.getName());
            address.setText(Instructor.getAddress());
            String Gender = Instructor.getGender();
            if ("Male".equals(Gender)){
                male.setSelected(true);
                male.setActionCommand("Male");
            }
            else{
                female.setSelected(true);
                female.setActionCommand("Female");
            }
            email.setText(Instructor.getEmail());
            nic.setText(Instructor.getNic());
            contactNumber.setText(Instructor.getContact_number());
        }else{
            JOptionPane.showMessageDialog(this, "Instructor Not Found");
            instructorid.setText(null);
        }
    } catch (SQLException ex) {
        Logger.getLogger(manage_lecturer.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void confirmButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonKeyPressed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        new manage_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void instructoridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructoridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructoridActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_instructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JTextField address;
    private javax.swing.JLabel address_Label;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JLabel contactNumber_Label;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_Label;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel gender_Label;
    private javax.swing.JPanel getInstructorIDPanel;
    private javax.swing.JTextField instructorID;
    private javax.swing.JLabel instructorID_Label;
    private javax.swing.JTextField instructorid;
    private javax.swing.JLabel instructorid_Label;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel manageInstructorLabel;
    private javax.swing.JPanel manageInstructorPanel;
    private javax.swing.JLabel manageInstructor_Label;
    private javax.swing.JPanel manageLecturerHeader;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_Label;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel nic_Label;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
