/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.paymentController;
import Controller.semesterController;
import Controller.studentSubjectController;
import Controller.undergraduateController;
import Model.payment;
import Model.semester;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashera
 */
public class payment_details extends javax.swing.JFrame {
    private final DefaultListModel subjectListModel =new DefaultListModel();
    
    /**
     * Creates new form payment
     */
    public payment_details() {
        initComponents();
        paymentDetails.setVisible(false);
        homeButton.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentStatus = new javax.swing.ButtonGroup();
        semesterGroup = new javax.swing.ButtonGroup();
        paymentHeader = new javax.swing.JPanel();
        paymentHeader_Label = new javax.swing.JLabel();
        home_Label = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        getDetails = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        semesterNumber_Label = new javax.swing.JLabel();
        academicYear_Label = new javax.swing.JLabel();
        academicYearCombo = new javax.swing.JComboBox<>();
        semester1 = new javax.swing.JRadioButton();
        semester2 = new javax.swing.JRadioButton();
        studentID_Label1 = new javax.swing.JLabel();
        getStudentID = new javax.swing.JTextField();
        paymentDetails = new javax.swing.JPanel();
        studentID_Label = new javax.swing.JLabel();
        paidStatus_label = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        notPaid = new javax.swing.JRadioButton();
        paid = new javax.swing.JRadioButton();
        studentID = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedSubjectList = new javax.swing.JList<>();
        semesterID_Label = new javax.swing.JLabel();
        semesterID = new javax.swing.JTextField();
        finalPayment_Label = new javax.swing.JLabel();
        totalPayment = new javax.swing.JTextField();
        subjectList_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        paymentHeader.setBackground(new java.awt.Color(36, 47, 65));
        paymentHeader.setLayout(null);

        paymentHeader_Label.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        paymentHeader_Label.setForeground(new java.awt.Color(255, 255, 255));
        paymentHeader_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentHeader_Label.setText("PAYMENT DETAILS");
        paymentHeader.add(paymentHeader_Label);
        paymentHeader_Label.setBounds(0, 13, 900, 64);

        home_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        paymentHeader.add(home_Label);
        home_Label.setBounds(0, 0, 90, 90);

        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        paymentHeader.add(homeButton);
        homeButton.setBounds(0, 0, 90, 90);

        getContentPane().add(paymentHeader);
        paymentHeader.setBounds(0, 0, 930, 90);

        getDetails.setBackground(new java.awt.Color(97, 212, 195));
        getDetails.setLayout(null);

        confirmButton.setBackground(new java.awt.Color(36, 47, 65));
        confirmButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.setBorder(null);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        confirmButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmButtonKeyPressed(evt);
            }
        });
        getDetails.add(confirmButton);
        confirmButton.setBounds(490, 300, 150, 50);

        backButton1.setBackground(new java.awt.Color(36, 47, 65));
        backButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        getDetails.add(backButton1);
        backButton1.setBounds(300, 300, 150, 50);

        semesterNumber_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semesterNumber_Label.setText("Semester Number");
        getDetails.add(semesterNumber_Label);
        semesterNumber_Label.setBounds(280, 130, 180, 30);

        academicYear_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        academicYear_Label.setText("Academic Year");
        getDetails.add(academicYear_Label);
        academicYear_Label.setBounds(280, 80, 180, 30);

        academicYearCombo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        academicYearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        getDetails.add(academicYearCombo);
        academicYearCombo.setBounds(500, 80, 150, 30);

        semesterGroup.add(semester1);
        semester1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        semester1.setText("1st Semester");
        semester1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester1ActionPerformed(evt);
            }
        });
        getDetails.add(semester1);
        semester1.setBounds(500, 130, 150, 30);

        semesterGroup.add(semester2);
        semester2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        semester2.setText("2nd Semester");
        semester2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester2ActionPerformed(evt);
            }
        });
        getDetails.add(semester2);
        semester2.setBounds(500, 180, 150, 30);

        studentID_Label1.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        studentID_Label1.setText("Student ID");
        getDetails.add(studentID_Label1);
        studentID_Label1.setBounds(280, 30, 180, 30);

        getStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStudentIDActionPerformed(evt);
            }
        });
        getDetails.add(getStudentID);
        getStudentID.setBounds(500, 30, 150, 30);

        getContentPane().add(getDetails);
        getDetails.setBounds(0, 90, 930, 430);

        paymentDetails.setBackground(new java.awt.Color(97, 212, 195));
        paymentDetails.setLayout(null);

        studentID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        studentID_Label.setText("Student ID");
        paymentDetails.add(studentID_Label);
        studentID_Label.setBounds(40, 110, 160, 30);

        paidStatus_label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        paidStatus_label.setText("Paid Status");
        paymentDetails.add(paidStatus_label);
        paidStatus_label.setBounds(280, 370, 210, 30);

        doneButton.setBackground(new java.awt.Color(36, 47, 65));
        doneButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(doneButton);
        doneButton.setBounds(500, 430, 120, 50);

        paymentStatus.add(notPaid);
        notPaid.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        notPaid.setText("Not Paid");
        notPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notPaidActionPerformed(evt);
            }
        });
        paymentDetails.add(notPaid);
        notPaid.setBounds(560, 370, 110, 31);

        paymentStatus.add(paid);
        paid.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        paid.setText("Paid");
        paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidActionPerformed(evt);
            }
        });
        paymentDetails.add(paid);
        paid.setBounds(440, 370, 110, 31);

        studentID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });
        paymentDetails.add(studentID);
        studentID.setBounds(200, 110, 230, 30);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(backButton);
        backButton.setBounds(330, 430, 120, 50);

        selectedSubjectList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(selectedSubjectList);

        paymentDetails.add(jScrollPane1);
        jScrollPane1.setBounds(205, 160, 490, 130);

        semesterID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semesterID_Label.setText("Semester ID");
        paymentDetails.add(semesterID_Label);
        semesterID_Label.setBounds(450, 110, 160, 30);

        semesterID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        semesterID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterIDActionPerformed(evt);
            }
        });
        paymentDetails.add(semesterID);
        semesterID.setBounds(610, 110, 230, 30);

        finalPayment_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        finalPayment_Label.setText("Total Payment");
        paymentDetails.add(finalPayment_Label);
        finalPayment_Label.setBounds(280, 320, 160, 30);

        totalPayment.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        totalPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPaymentActionPerformed(evt);
            }
        });
        paymentDetails.add(totalPayment);
        totalPayment.setBounds(440, 320, 230, 30);

        subjectList_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        subjectList_Label.setText("Subject List");
        paymentDetails.add(subjectList_Label);
        subjectList_Label.setBounds(40, 160, 160, 30);

        getContentPane().add(paymentDetails);
        paymentDetails.setBounds(0, 0, 920, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        String ID = studentID.getText();
        int semester_id = Integer.parseInt(semesterID.getText());
        String isPaid = paymentStatus.getSelection().getActionCommand();
        
        boolean is_paid;
        if ("1".equals(isPaid))
            is_paid = true;
        else
            is_paid = false;

        payment Payment = new payment(is_paid,ID,semester_id);
        try{
            int result = paymentController.addPaymentStudentDetails(Payment);
            if ( result>0 ) {
                JOptionPane.showMessageDialog(this,"Successful");
                new homepage().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this,"Error");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
       
    }//GEN-LAST:event_doneButtonActionPerformed

    private void notPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notPaidActionPerformed
        notPaid.setActionCommand("0");
    }//GEN-LAST:event_notPaidActionPerformed

    private void paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidActionPerformed
        paid.setActionCommand("1");
    }//GEN-LAST:event_paidActionPerformed

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void semesterIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterIDActionPerformed

    private void totalPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPaymentActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        String student_id = getStudentID.getText();
        String academic_year = (String) academicYearCombo.getSelectedItem();
        String semester_number = semesterGroup.getSelection().getActionCommand();
        int year;
        if (null == academic_year)
        year = 4;
        else switch (academic_year) {
            case "1st Year":
            year = 1;
            break;
            case "2nd Year":
            year = 2;
            break;
            case "3rd Year":
            year = 3;
            break;
            default:
            year = 4;
            break;
        }
        semester sem = new semester(year, Integer.parseInt(semester_number));
        try {
            ResultSet rs = undergraduateController.checkStudentID(student_id);
            if (rs.next()) {
                int semesterid = semesterController.findSemesterID(sem);
                int result = paymentController.checkStudentEnrolment(student_id, semesterid);
                if (result==1){
                    getDetails.setVisible(false);
                    paymentDetails.setVisible(true);
                    studentID.setEditable(false);
                    studentID.setText(student_id);
                    semesterID.setEditable(false);
                    semesterID.setText(Integer.toString(semesterid));
                    totalPayment.setEditable(false);
                    totalPayment.setText(Double.toString(paymentController.findTotalPayment(student_id, semesterid)));
                    ArrayList<String> list = new ArrayList<>();
                    list = studentSubjectController.getFollowingSubjectList(student_id, semesterid);
                    for (String subject : list) {
                        subjectListModel.addElement(subject);
                    }
                    selectedSubjectList.setModel(subjectListModel);
                }else {
                    JOptionPane.showMessageDialog(this, "Subjects Not Selected");
                    studentID.setText(null);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Student Not Found");
                getStudentID.setText(null);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void confirmButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonKeyPressed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void semester1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester1ActionPerformed
        semester1.setActionCommand("1");
    }//GEN-LAST:event_semester1ActionPerformed

    private void semester2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester2ActionPerformed
        semester2.setActionCommand("2");
    }//GEN-LAST:event_semester2ActionPerformed

    private void getStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getStudentIDActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> academicYearCombo;
    private javax.swing.JLabel academicYear_Label;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel finalPayment_Label;
    private javax.swing.JPanel getDetails;
    private javax.swing.JTextField getStudentID;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel home_Label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton notPaid;
    private javax.swing.JRadioButton paid;
    private javax.swing.JLabel paidStatus_label;
    private javax.swing.JPanel paymentDetails;
    private javax.swing.JPanel paymentHeader;
    private javax.swing.JLabel paymentHeader_Label;
    private javax.swing.ButtonGroup paymentStatus;
    private javax.swing.JList<String> selectedSubjectList;
    private javax.swing.JRadioButton semester1;
    private javax.swing.JRadioButton semester2;
    private javax.swing.ButtonGroup semesterGroup;
    private javax.swing.JTextField semesterID;
    private javax.swing.JLabel semesterID_Label;
    private javax.swing.JLabel semesterNumber_Label;
    private javax.swing.JTextField studentID;
    private javax.swing.JLabel studentID_Label;
    private javax.swing.JLabel studentID_Label1;
    private javax.swing.JLabel subjectList_Label;
    private javax.swing.JTextField totalPayment;
    // End of variables declaration//GEN-END:variables
}
