/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.assignmentController;
import Controller.mailController;
import Controller.studentSubjectController;
import Controller.subjectController;
import Controller.undergraduateController;
import Model.mark;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashera
 */
public class report extends javax.swing.JFrame {
    public static String emailMsgTxt = "";
    private static String emailSubjectTxt = "";
    private static String emailFromAddress = "";
    // Add List of Email address to who email needs to be sent to
    private static String[] emailList = new String[10];
    
    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        homeButton.setContentAreaFilled(false);
        gpa.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportHeader = new javax.swing.JPanel();
        reportHeader_Label = new javax.swing.JLabel();
        home_Label = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        paymentDetails = new javax.swing.JPanel();
        studentID_Label = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        gpa_Label = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        semesterID_Label = new javax.swing.JLabel();
        semesterID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        generateReportButton = new javax.swing.JButton();
        sendEmailButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        reportHeader.setBackground(new java.awt.Color(36, 47, 65));
        reportHeader.setLayout(null);

        reportHeader_Label.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        reportHeader_Label.setForeground(new java.awt.Color(255, 255, 255));
        reportHeader_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportHeader_Label.setText("GENERATE REPORT");
        reportHeader.add(reportHeader_Label);
        reportHeader_Label.setBounds(0, 13, 900, 64);

        home_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        reportHeader.add(home_Label);
        home_Label.setBounds(0, 0, 90, 90);

        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        reportHeader.add(homeButton);
        homeButton.setBounds(0, 0, 90, 90);

        getContentPane().add(reportHeader);
        reportHeader.setBounds(0, 0, 910, 90);

        paymentDetails.setBackground(new java.awt.Color(97, 212, 195));
        paymentDetails.setLayout(null);

        studentID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        studentID_Label.setText("Student ID");
        paymentDetails.add(studentID_Label);
        studentID_Label.setBounds(100, 110, 210, 30);

        studentID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });
        paymentDetails.add(studentID);
        studentID.setBounds(310, 110, 230, 30);

        backButton.setBackground(new java.awt.Color(36, 47, 65));
        backButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(backButton);
        backButton.setBounds(290, 430, 150, 50);

        gpa_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        gpa_Label.setText("Semester GPA");
        paymentDetails.add(gpa_Label);
        gpa_Label.setBounds(240, 370, 210, 30);

        gpa.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaActionPerformed(evt);
            }
        });
        paymentDetails.add(gpa);
        gpa.setBounds(480, 370, 230, 30);

        semesterID_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semesterID_Label.setText("Semester ID");
        paymentDetails.add(semesterID_Label);
        semesterID_Label.setBounds(100, 150, 210, 30);

        semesterID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        semesterID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterIDActionPerformed(evt);
            }
        });
        paymentDetails.add(semesterID);
        semesterID.setBounds(310, 150, 230, 30);

        resultsTable.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Result"
            }
        ));
        jScrollPane1.setViewportView(resultsTable);

        paymentDetails.add(jScrollPane1);
        jScrollPane1.setBounds(145, 200, 610, 150);

        generateReportButton.setBackground(new java.awt.Color(36, 47, 65));
        generateReportButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        generateReportButton.setForeground(new java.awt.Color(255, 255, 255));
        generateReportButton.setText("Generate Report");
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(generateReportButton);
        generateReportButton.setBounds(650, 130, 160, 30);

        sendEmailButton.setBackground(new java.awt.Color(36, 47, 65));
        sendEmailButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        sendEmailButton.setForeground(new java.awt.Color(255, 255, 255));
        sendEmailButton.setText("Send Email");
        sendEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(sendEmailButton);
        sendEmailButton.setBounds(710, 430, 170, 50);

        resetButton.setBackground(new java.awt.Color(36, 47, 65));
        resetButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        paymentDetails.add(resetButton);
        resetButton.setBounds(490, 430, 120, 50);

        getContentPane().add(paymentDetails);
        paymentDetails.setBounds(0, 0, 920, 520);

        setSize(new java.awt.Dimension(918, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String findGrade(double marks){
        if (marks>=90)
            return "A+";
        else if (marks>=80)
            return "A";
        else if (marks>=75)
            return "A-";
        else if (marks>=70)
            return "B+";
        else if (marks>=65)
            return "B";
        else if (marks>=60)
            return "B-";
        else if (marks>=55)
            return "C+";
        else if (marks>=50)
            return "C";
        else if (marks>=45)
            return "C-";
        else
            return "F";
    }
    
    private double findGPV(double marks){
        if (marks>=90)
            return 4.25;
        else if (marks>=80)
            return 4.00;
        else if (marks>=75)
            return 3.75;
        else if (marks>=70)
            return 3.25;
        else if (marks>=65)
            return 3.00;
        else if (marks>=60)
            return 2.75;
        else if (marks>=55)
            return 2.25;
        else if (marks>=50)
            return 2.00;
        else if (marks>=45)
            return 1.75;
        else
            return 0.00;
    }
    
    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new manage_results().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void gpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaActionPerformed

    private void semesterIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterIDActionPerformed

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) resultsTable.getModel();
        int totalCredits=0;
        double GPA=0;
        String student_id = studentID.getText();
        int semester_id = Integer.parseInt(semesterID.getText());

        try{
            ResultSet studentCheck = undergraduateController.checkStudentID(student_id);
            if (studentCheck.next()){
                generateReportButton.setEnabled(false);
                studentID.setEditable(false);
                semesterID.setEditable(false);
                ArrayList<String> subjectCodeList = studentSubjectController.getFollowingSubjectCodeList(student_id, semester_id);
                for (String subj : subjectCodeList) {
                    double totalMark = 0;
                    int examMark = assignmentController.getExamMark(student_id,subj);// Exam weight is 50
                    totalMark+=examMark*0.5;
                    ArrayList<mark> assignmentMarks = assignmentController.getMarkWeight(student_id, subj);
                    for (mark temp : assignmentMarks) {
                        totalMark+=temp.getMark()*temp.getWeight()/100.0;
                    }
                    
                    //Assigning the grade to the final mark obtained for the subject
                    String grade = findGrade(totalMark);
                    
                    String subject_name = subjectController.getSubjectName(subj);  
                    model.addRow(new Object[]{subject_name,grade});
                    emailMsgTxt+=subject_name+"\t\t:\t"+grade+"\n";
                    
                    //Calculating the number of credits for the subject
                    int tempCredit = subjectController.getCredits(subj);
                    totalCredits+=tempCredit;
                    GPA+=findGPV(totalMark)*tempCredit;
                }
                GPA/=totalCredits;
                gpa.setText(Double.toString(GPA));
                emailMsgTxt+="\nNumber of credits covered : "+totalCredits+"\nSemester GPA : "+GPA;
            }
            else{
                JOptionPane.showMessageDialog(this, "Student Not Found");
                studentID.setText(null);
                semesterID.setText(null);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_generateReportButtonActionPerformed

    private void sendEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailButtonActionPerformed
//        emailMsgTxt = "Testing the content in email";
        emailSubjectTxt = "Overview of Index Number : "+studentID.getText();
        emailFromAddress = mailController.SMTP_AUTH_USER;

        // Add List of Email address to who email needs to be sent to
        String emailReceipeint[] = new String[1];
        try {
            emailList[0] = undergraduateController.getStudentEmailAddress(studentID.getText());
            emailReceipeint[0] = emailList[0];
        } catch (SQLException ex) {
            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
        }
              
        mailController smtpMailSender = new mailController();
        try {
            smtpMailSender.postMail(emailReceipeint, emailSubjectTxt, emailMsgTxt, emailFromAddress);
            JOptionPane.showMessageDialog(this, "Sucessfully Sent Mail");
        } catch (MessagingException ex) {
            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendEmailButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) resultsTable.getModel();
        model.setRowCount(0);
        generateReportButton.setEnabled(true);
        studentID.setEditable(true);
        semesterID.setEditable(true);
        studentID.setText(null);
        semesterID.setText(null);
        gpa.setText(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JTextField gpa;
    private javax.swing.JLabel gpa_Label;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel home_Label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paymentDetails;
    private javax.swing.JPanel reportHeader;
    private javax.swing.JLabel reportHeader_Label;
    private javax.swing.JButton resetButton;
    private javax.swing.JTable resultsTable;
    private javax.swing.JTextField semesterID;
    private javax.swing.JLabel semesterID_Label;
    private javax.swing.JButton sendEmailButton;
    private javax.swing.JTextField studentID;
    private javax.swing.JLabel studentID_Label;
    // End of variables declaration//GEN-END:variables
}
