/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import Controller.courseController;
import Controller.studentSubjectController;
import Controller.subjectController;
import Model.student_subject_semester;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashera
 */
public class subject_selection extends javax.swing.JFrame {
    public static String student_id;
    public static String intake_month=null;
    public static boolean is_undergraduate;
    public static int academicYear;
    public static String courseID;
    private final DefaultListModel sem1SubjectsModel =new DefaultListModel();
    private final DefaultListModel sem1SelectedModel =new DefaultListModel();
    private final DefaultListModel sem2SubjectsModel =new DefaultListModel();
    private final DefaultListModel sem2SelectedModel =new DefaultListModel();
    
    /**
     * Creates new form subject_selection
     */
    public subject_selection() {
        initComponents();
        if ("July".equals(intake_month))
            sem1Panel.setVisible(false);
        try {
            displaySubjects();
        } catch (SQLException ex) {
            Logger.getLogger(subject_selection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        subjectSelectionHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sem1Panel = new javax.swing.JPanel();
        sem1ScrollPane = new javax.swing.JScrollPane();
        sem1SubjectList = new javax.swing.JList<>();
        sem1ScrollPane1 = new javax.swing.JScrollPane();
        sem1SubjectSelectedList = new javax.swing.JList<>();
        semester1_Label = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        addSem1SubjectButton = new javax.swing.JButton();
        removeSem1SubjectButton = new javax.swing.JButton();
        sem2Panel = new javax.swing.JPanel();
        semester2_Label = new javax.swing.JLabel();
        sem2ScrollPane = new javax.swing.JScrollPane();
        sem2SubjectList = new javax.swing.JList<>();
        sem2ScrollPane1 = new javax.swing.JScrollPane();
        sem2SubjectSelectedList = new javax.swing.JList<>();
        label1 = new javax.swing.JLabel();
        removeSem2SubjectButton = new javax.swing.JButton();
        addSem2SubjectButton = new javax.swing.JButton();
        addSubjectsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(null);

        subjectSelectionHeader.setBackground(new java.awt.Color(36, 47, 65));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUBJECT SELECTION");

        javax.swing.GroupLayout subjectSelectionHeaderLayout = new javax.swing.GroupLayout(subjectSelectionHeader);
        subjectSelectionHeader.setLayout(subjectSelectionHeaderLayout);
        subjectSelectionHeaderLayout.setHorizontalGroup(
            subjectSelectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectSelectionHeaderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        subjectSelectionHeaderLayout.setVerticalGroup(
            subjectSelectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subjectSelectionHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(subjectSelectionHeader);
        subjectSelectionHeader.setBounds(0, 0, 940, 90);

        sem1Panel.setBackground(new java.awt.Color(97, 212, 195));
        sem1Panel.setLayout(null);

        sem1ScrollPane.setBackground(new java.awt.Color(0, 0, 0));

        sem1SubjectList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        sem1SubjectList.setSelectionBackground(new java.awt.Color(36, 47, 65));
        sem1ScrollPane.setViewportView(sem1SubjectList);

        sem1Panel.add(sem1ScrollPane);
        sem1ScrollPane.setBounds(20, 100, 150, 150);

        sem1ScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        sem1SubjectSelectedList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        sem1SubjectSelectedList.setSelectionBackground(new java.awt.Color(36, 47, 65));
        sem1ScrollPane1.setViewportView(sem1SubjectSelectedList);

        sem1Panel.add(sem1ScrollPane1);
        sem1ScrollPane1.setBounds(270, 100, 150, 150);

        semester1_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semester1_Label.setText("Semester 1");
        sem1Panel.add(semester1_Label);
        semester1_Label.setBounds(20, 20, 180, 30);

        label.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        label.setText("Select at most 4");
        sem1Panel.add(label);
        label.setBounds(20, 50, 180, 30);

        addSem1SubjectButton.setBackground(new java.awt.Color(36, 47, 65));
        addSem1SubjectButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        addSem1SubjectButton.setForeground(new java.awt.Color(255, 255, 255));
        addSem1SubjectButton.setText("Add");
        addSem1SubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSem1SubjectButtonActionPerformed(evt);
            }
        });
        sem1Panel.add(addSem1SubjectButton);
        addSem1SubjectButton.setBounds(180, 130, 80, 30);

        removeSem1SubjectButton.setBackground(new java.awt.Color(36, 47, 65));
        removeSem1SubjectButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        removeSem1SubjectButton.setForeground(new java.awt.Color(255, 255, 255));
        removeSem1SubjectButton.setText("Remove");
        removeSem1SubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSem1SubjectButtonActionPerformed(evt);
            }
        });
        sem1Panel.add(removeSem1SubjectButton);
        removeSem1SubjectButton.setBounds(180, 180, 80, 30);

        jPanel2.add(sem1Panel);
        sem1Panel.setBounds(0, 90, 450, 320);

        sem2Panel.setBackground(new java.awt.Color(97, 212, 195));
        sem2Panel.setLayout(null);

        semester2_Label.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        semester2_Label.setText("Semester 2");
        sem2Panel.add(semester2_Label);
        semester2_Label.setBounds(20, 20, 180, 30);

        sem2ScrollPane.setBackground(new java.awt.Color(0, 0, 0));

        sem2SubjectList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        sem2SubjectList.setSelectionBackground(new java.awt.Color(36, 47, 65));
        sem2ScrollPane.setViewportView(sem2SubjectList);

        sem2Panel.add(sem2ScrollPane);
        sem2ScrollPane.setBounds(20, 100, 150, 150);

        sem2ScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        sem2SubjectSelectedList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        sem2SubjectSelectedList.setSelectionBackground(new java.awt.Color(36, 47, 65));
        sem2ScrollPane1.setViewportView(sem2SubjectSelectedList);

        sem2Panel.add(sem2ScrollPane1);
        sem2ScrollPane1.setBounds(270, 100, 150, 150);

        label1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        label1.setText("Select at most 4");
        sem2Panel.add(label1);
        label1.setBounds(20, 50, 180, 30);

        removeSem2SubjectButton.setBackground(new java.awt.Color(36, 47, 65));
        removeSem2SubjectButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        removeSem2SubjectButton.setForeground(new java.awt.Color(255, 255, 255));
        removeSem2SubjectButton.setText("Remove");
        removeSem2SubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSem2SubjectButtonActionPerformed(evt);
            }
        });
        sem2Panel.add(removeSem2SubjectButton);
        removeSem2SubjectButton.setBounds(180, 180, 80, 30);

        addSem2SubjectButton.setBackground(new java.awt.Color(36, 47, 65));
        addSem2SubjectButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        addSem2SubjectButton.setForeground(new java.awt.Color(255, 255, 255));
        addSem2SubjectButton.setText("Add");
        addSem2SubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSem2SubjectButtonActionPerformed(evt);
            }
        });
        sem2Panel.add(addSem2SubjectButton);
        addSem2SubjectButton.setBounds(180, 130, 80, 30);

        jPanel2.add(sem2Panel);
        sem2Panel.setBounds(470, 90, 450, 320);

        addSubjectsButton.setBackground(new java.awt.Color(36, 47, 65));
        addSubjectsButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        addSubjectsButton.setForeground(new java.awt.Color(255, 255, 255));
        addSubjectsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addSubjectsButton.setText("Add");
        addSubjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addSubjectsButton);
        addSubjectsButton.setBounds(395, 420, 120, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 520);

        setSize(new java.awt.Dimension(928, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void displaySubjects() throws SQLException {
        ArrayList<String> subjectListSem1 = new ArrayList();
        ArrayList<String> subjectListSem2 = new ArrayList();
        if (is_undergraduate) {
            courseID = courseController.getUndergraduateCourseID(student_id);
        }
        else{
            courseID = courseController.getPostgraduateCourseID(student_id);
        }
        try {
            subjectListSem1 = subjectController.getSubjects(courseID,2*academicYear-1,false);
            subjectListSem2 = subjectController.getSubjects(courseID,2*academicYear,false);
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        for (String subject : subjectListSem1) {
            sem1SubjectsModel.addElement(subject);
        }
        for (String subject : subjectListSem2) {
            sem2SubjectsModel.addElement(subject);
        }
        sem1SubjectList.setModel(sem1SubjectsModel);
        sem2SubjectList.setModel(sem2SubjectsModel);
    }
    
    private void addSubjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectsButtonActionPerformed
        int size1 = sem1SubjectSelectedList.getModel().getSize();
        int size2 = sem2SubjectSelectedList.getModel().getSize();
        ArrayList<String> sem1_list = new ArrayList<>();
        ArrayList<String> sem2_list = new ArrayList<>();
        
        if (!"July".equals(intake_month)){
            try {
                sem1_list = subjectController.getCompulsorySubjects(courseID,2*academicYear-1,true);
                for (String subject:sem1_list) {
                    student_subject_semester addsubject = new student_subject_semester(student_id,subject,2*academicYear-1);
                    studentSubjectController.addStudentSubject(addsubject);
                }
            } catch (SQLException ex) {
                Logger.getLogger(subject_selection.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (int i=0;i<size1;i++) {
                String subject_code;
                try {
                    subject_code = subjectController.getSubjectCode(sem1SubjectSelectedList.getModel().getElementAt(i));
                    student_subject_semester addsubject = new student_subject_semester(student_id,subject_code,2*academicYear-1);
                    studentSubjectController.addStudentSubject(addsubject);
                } catch (SQLException ex) {
                    Logger.getLogger(subject_selection.class.getName()).log(Level.SEVERE, null, ex);
                }  
            }
            
        }

        try {
            sem2_list = subjectController.getCompulsorySubjects(courseID,2*academicYear,true);
            for (String compulsorySubject:sem2_list) {
                student_subject_semester addsubject = new student_subject_semester(student_id,compulsorySubject,2*academicYear);
                studentSubjectController.addStudentSubject(addsubject);
            }
        } catch (SQLException ex) {
            Logger.getLogger(subject_selection.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i=0;i<size2;i++) {
            String subject_code;
            try {
                subject_code = subjectController.getSubjectCode(sem2SubjectSelectedList.getModel().getElementAt(i));
                student_subject_semester addsubject = new student_subject_semester(student_id,subject_code,2*academicYear);
                studentSubjectController.addStudentSubject(addsubject);
            } catch (SQLException ex) {
                Logger.getLogger(subject_selection.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }  
        JOptionPane.showMessageDialog(this,"Successfully Added Subjects");
        new homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addSubjectsButtonActionPerformed

    private void addSem1SubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSem1SubjectButtonActionPerformed
        if(sem1SubjectList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this,"No Subject Selected");
        }
        else {
            if(sem1SelectedModel.size()<4) {
                sem1SelectedModel.addElement(sem1SubjectList.getSelectedValue());
                sem1SubjectsModel.remove(sem1SubjectList.getSelectedIndex());
                sem1SubjectList.setModel(sem1SubjectsModel);
                sem1SubjectSelectedList.setModel(sem1SelectedModel);
            }
            else {
                JOptionPane.showMessageDialog(this, "Subject Limit Reached");
            }
        }
    }//GEN-LAST:event_addSem1SubjectButtonActionPerformed

    private void removeSem1SubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSem1SubjectButtonActionPerformed
        if(sem1SubjectSelectedList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this,"No Subject Selected");
        }
        else {
            sem1SubjectsModel.addElement(sem1SubjectSelectedList.getSelectedValue());
            sem1SelectedModel.remove(sem1SubjectSelectedList.getSelectedIndex());
            sem1SubjectList.setModel(sem1SubjectsModel);
            sem1SubjectSelectedList.setModel(sem1SelectedModel);
        }
    }//GEN-LAST:event_removeSem1SubjectButtonActionPerformed

    private void addSem2SubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSem2SubjectButtonActionPerformed
         if(sem2SubjectList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this,"No Subject Selected");
        }
        else {
            if(sem2SelectedModel.size()<4) {
                sem2SelectedModel.addElement(sem2SubjectList.getSelectedValue());
                sem2SubjectsModel.remove(sem2SubjectList.getSelectedIndex());
                sem2SubjectList.setModel(sem2SubjectsModel);
                sem2SubjectSelectedList.setModel(sem2SelectedModel);
            }
            else {
                JOptionPane.showMessageDialog(this, "Subject Limit Reached");
            }
        }
    }//GEN-LAST:event_addSem2SubjectButtonActionPerformed

    private void removeSem2SubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSem2SubjectButtonActionPerformed
        if(sem2SubjectSelectedList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this,"No Subject Selected");
        }
        else {
            sem2SubjectsModel.addElement(sem2SubjectSelectedList.getSelectedValue());
            sem2SelectedModel.remove(sem2SubjectSelectedList.getSelectedIndex());
            sem2SubjectList.setModel(sem2SubjectsModel);
            sem2SubjectSelectedList.setModel(sem2SelectedModel);
        }
    }//GEN-LAST:event_removeSem2SubjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subject_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subject_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subject_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subject_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subject_selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSem1SubjectButton;
    private javax.swing.JButton addSem2SubjectButton;
    private javax.swing.JButton addSubjectsButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JButton nextPageButton;
    private javax.swing.JButton nextPageButton1;
    private javax.swing.JButton removeSem1SubjectButton;
    private javax.swing.JButton removeSem2SubjectButton;
    private javax.swing.JPanel sem1Panel;
    private javax.swing.JScrollPane sem1ScrollPane;
    private javax.swing.JScrollPane sem1ScrollPane1;
    private javax.swing.JList<String> sem1SubjectList;
    private javax.swing.JList<String> sem1SubjectSelectedList;
    private javax.swing.JPanel sem2Panel;
    private javax.swing.JScrollPane sem2ScrollPane;
    private javax.swing.JScrollPane sem2ScrollPane1;
    private javax.swing.JList<String> sem2SubjectList;
    private javax.swing.JList<String> sem2SubjectSelectedList;
    private javax.swing.JLabel semester1_Label;
    private javax.swing.JLabel semester2_Label;
    private javax.swing.JPanel subjectSelectionHeader;
    // End of variables declaration//GEN-END:variables
}
